#!/usr/bin/env bash
# IA-Dev-Hub — First-run bootstrap script.
# Creates ~/iah/ data directory, generates .env, seeds openclaw.json and
# rule templates, starts Docker Compose, and installs the IDH plugin.
#
# Run once:          ./setup.sh
# Subsequent starts: docker compose up -d
#
# NOTE: Step order follows the spec (Section 1.5) with two additions:
# - Pre-populating known_hosts (moved earlier for convenience)
# - Seeding CODING_RULES.md and COMMON_CONTEXT.md templates (not in spec — extension)

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[IDH]${NC} $1"; }
warn() { echo -e "${YELLOW}[IDH]${NC} $1"; }
err()  { echo -e "${RED}[IDH]${NC} $1"; exit 1; }

IAH_DIR="$HOME/iah"

# --- Step 1: Create data directory tree ---
log "Creating data directory at $IAH_DIR ..."
mkdir -p "$IAH_DIR"/{config,workspaces,state,rules}

# --- Step 2: Generate .env if it doesn't exist ---
ENV_FILE="$IAH_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    log "Generating $ENV_FILE ..."

    read -rp "Telegram bot token (from BotFather): " TELEGRAM_BOT_TOKEN
    [ -z "$TELEGRAM_BOT_TOKEN" ] && err "Telegram bot token is required."

    read -rp "Your Telegram user ID (numeric): " TELEGRAM_USER_ID
    [ -z "$TELEGRAM_USER_ID" ] && err "Telegram user ID is required."

    read -rp "Bridge TTL in hours [8]: " BRIDGE_TTL_HOURS
    BRIDGE_TTL_HOURS="${BRIDGE_TTL_HOURS:-8}"

    # Auto-generate a random webhook secret (not prompted -- not a human-readable value)
    IDH_WEBHOOK_SECRET=$(openssl rand -hex 32)

    cat > "$ENV_FILE" <<EOF
# IA-Dev-Hub environment variables -- generated by setup.sh

# --- Telegram ---
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_USER_ID=${TELEGRAM_USER_ID}

# --- IDH ---
BRIDGE_TTL_HOURS=${BRIDGE_TTL_HOURS}
IDH_WEBHOOK_SECRET=${IDH_WEBHOOK_SECRET}

# --- Ports (change if there are conflicts on your host) ---
OPENCLAW_GATEWAY_PORT=18789
OPENCLAW_DASHBOARD_PORT=18790
IDH_APP_PORT=8000
CODE_SERVER_PORT=8443

# --- FastAPI ---
FASTAPI_APP_NAME=IDH App
FASTAPI_DEBUG_MODE=false
CORS_ALLOWED_ORIGINS=*

# --- Logging ---
LOGGING_CONSOLE_LEVEL=INFO
LOGGING_FILE_LEVEL=DEBUG
LOGGING_ENABLE_CONSOLE=true
LOGGING_ENABLE_FILE=false
LOGGING_LPP_FORMAT=ShortFormat
EOF
    log ".env created."
else
    warn ".env already exists at $ENV_FILE -- skipping."
fi

# --- Step 3: Generate minimal openclaw.json if not present ---
OPENCLAW_JSON="$IAH_DIR/config/openclaw.json"
if [ ! -f "$OPENCLAW_JSON" ]; then
    log "Generating openclaw.json ..."
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    cat > "$OPENCLAW_JSON" <<EOF
{
  "gateway": {
    "bind": "lan",
    "mode": "local"
  },
  "channels": {
    "telegram": {
      "enabled": true,
      "botToken": "${TELEGRAM_BOT_TOKEN}",
      "groupPolicy": "allowlist",
      "dmPolicy": "disabled",
      "groups": {}
    }
  },
  "auth": {
    "allowFrom": ["${TELEGRAM_USER_ID}"]
  }
}
EOF
    log "openclaw.json created."
else
    warn "openclaw.json already exists -- skipping."
fi

# --- Step 4: Pre-populate GitHub known_hosts ---
KNOWN_HOSTS="$HOME/.ssh/known_hosts"
if [ -f "$HOME/.ssh/id_ed25519" ]; then
    if ! grep -q "github.com" "$KNOWN_HOSTS" 2>/dev/null; then
        log "Adding GitHub to known_hosts ..."
        ssh-keyscan github.com >> "$KNOWN_HOSTS" 2>/dev/null
    fi
else
    warn "No SSH key at ~/.ssh/id_ed25519 -- git clone via SSH will not work."
    warn "Generate one: ssh-keygen -t ed25519 -C 'your@email.com'"
fi

# --- Step 5: Seed rule templates if not present (extension -- not in spec) ---
CODING_RULES="$IAH_DIR/rules/CODING_RULES.md"
COMMON_CONTEXT="$IAH_DIR/rules/COMMON_CONTEXT.md"

if [ ! -f "$CODING_RULES" ]; then
    cat > "$CODING_RULES" <<'EOF'
# Coding Rules

<!-- Edit this file to define your coding standards. -->
<!-- These rules are injected into CLAUDE.md for each project's coding agent. -->

## General
- Write clean, readable code with clear variable names.
- Add comments for non-obvious logic.
- Prefer explicit over implicit.
EOF
    log "CODING_RULES.md template created."
fi

if [ ! -f "$COMMON_CONTEXT" ]; then
    cat > "$COMMON_CONTEXT" <<'EOF'
# Common Context

<!-- Variables substituted at project creation: -->
<!-- {{PROJECT_ID}}, {{WORKSPACE_DIR}}, {{REPO_URL}} -->

You are working on project **{{PROJECT_ID}}**.
- Workspace: `{{WORKSPACE_DIR}}`
- Repository: `{{REPO_URL}}`
- Environment: Docker container on a Proxmox Debian 12 VM.
- Available tools: git, standard shell utilities.

Read `SESSION_MEMORY.md` at the start of every session -- it contains your working memory.
EOF
    log "COMMON_CONTEXT.md template created."
fi

# --- Step 6: Start Docker Compose ---
log "Building and starting Docker Compose ..."
docker compose up -d --build

log "Waiting for services to be healthy ..."
# Poll idh-app health endpoint instead of sleeping a fixed duration.
for i in $(seq 1 30); do
    if curl -sf "http://localhost:${IDH_APP_PORT:-8000}/api/v1/health/ping" > /dev/null 2>&1; then
        log "idh-app is healthy."
        break
    fi
    sleep 3
done

# --- Step 7: Install IDH plugin ---
log "Installing IDH plugin in openclaw-gateway ..."
# The plugin is mounted at /home/node/.openclaw/plugins/idh (read-only).
# The install command registers it in OpenClaw's extension registry.
docker exec openclaw-gateway openclaw extensions install \
    /home/node/.openclaw/plugins/idh || \
    warn "Plugin install step failed -- check openclaw-gateway logs."

log ""
log "IA-Dev-Hub is running!"
log "   OpenClaw gateway  : http://localhost:${OPENCLAW_GATEWAY_PORT:-18789}"
log "   OpenClaw dashboard: http://localhost:${OPENCLAW_DASHBOARD_PORT:-18790}"
log "   IDH App           : http://localhost:${IDH_APP_PORT:-8000}"
log "   VS Code Server    : http://localhost:${CODE_SERVER_PORT:-8443}"
log ""
log "Test plugin: send /idh_ping in any Telegram group the bot is in."
